#!/usr/bin/env bash
# Script to display DNS information about specified subdomains

function display_info {
    local domain=$1
    local subdomain=$2
    local record_type="A"
    local destination=$(dig +short "$subdomain.$domain")

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [[ -z $1 ]]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

domain=$1

if [[ -n $2 ]]; then
    display_info $domain $2
else
    for sub in "www" "54.80.212.49" "54.87.238.72" "35.153.52.13"; do
        display_info $domain $sub
    done
fi
