#!/usr/bin/env bash
# Bash script to configure nginx web server for redirection
# Update package lists
apt-get update -y

# Install nginx
apt-get install nginx -y

# Create a simple index page
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html

# Start nginx service
service nginx start

# Define the redirection configuration
rdt="location /redirect_me {\n    rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}"

# Insert the redirection configuration after the 'server {' block
sed -i '/^server {/a \\n'"$rdt" /etc/nginx/sites-available/default

# Restart nginx service to apply changes
service nginx restart

