#!/usr/bin/env bash

# Update package lists
sudo apt-get update -y

# Install nginx
sudo apt-get install nginx -y

# Define the custom 404 page content
not_found_page="Ceci n'est pas une page"

# Remove default error pages
sudo rm /etc/nginx/sites-available/default
sudo rm /etc/nginx/sites-enabled/default

# Create a new configuration file for default server
sudo tee /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
        echo "$not_found_page";
    }
}
EOF

# Create the custom 404 page
sudo tee /var/www/html/404.html <<EOF
<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
    <p>$not_found_page</p>
</body>
</html>
EOF

# Restart nginx service to apply changes
sudo systemctl restart nginx

