#!/usr/bin/env bash

# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Set custom HTTP response header
sudo sed -i '/server_name _;/a \        add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

# Restart nginx to apply changes
sudo systemctl restart nginx
