#!/usr/bin/env bash
# This script displays a list of currently running processes.

# Using ps command to display processes with user-oriented format, including all users and those without a TTY
# Sorting the processes by PID to show hierarchy
ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,cmd --forest
