#!/bin/bash

PID_FILE=/var/run/my_process.pid
PROCESS_FILE=/tmp/my_process

start_process() {
    bash manage_my_process &
    echo $! > $PID_FILE
    echo "manage_my_process started"
}

stop_process() {
    if [ -f $PID_FILE ]; then
        kill $(cat $PID_FILE)
        rm -f $PID_FILE
        echo "manage_my_process stopped"
    fi
}

restart_process() {
    stop_process
    start_process
    echo "manage_my_process restarted"
}

case $1 in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac
