#!/usr/bin/env bash
# This script displays lines containing the word "bash" to get the PID of the Bash process.

# Using ps command to list processes and grep to filter lines containing "bash"
ps aux | grep bash | grep -v grep

# shellcheck disable=SC2009
