#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process.

# Finding the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep 4-to_infinity_and_beyond)

# Checking if the PID is found
if [ -n "$pid" ]; then
    # Sending the SIGTERM signal to terminate the process
    kill -TERM "$pid"
fi
