#!/usr/bin/env bash
# This script tells the story of /etc/passwd

# Read each line of the /etc/passwd file and process it
while IFS=':' read -r username _ userid groupid gecos homedir shell; do
    # Extract the password from gecos field
    password=$(echo "$gecos" | cut -d',' -f1)
    # Extract user id info from gecos field
    userinfo=$(echo "$gecos" | cut -d',' -f5)

    # Print the story based on the extracted information
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd
