#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays the data

# Use awk to extract and count occurrences of each combination of IP and HTTP status code
awk '{ count[$1 " " $9]++ } END { for (key in count) print count[key], key }' apache-access.log | sort -rn
