#!/usr/bin/env bash
# This script displays "Best School" 10 times using an until loop

# Initialize counter
count=0

# Use an until loop to display "Best School" 10 times
until [ $count -eq 10 ]
do
    echo "Best School"
    # Increment counter
    ((count++))
done
