#!/usr/bin/env bash
# This script displays messages based on loop iteration

# Initialize counter
count=1

# Use a while loop to iterate from 1 to 10
while [ $count -le 10 ]
do
    # Check iteration number
    if [ $count -eq 4 ]; then
        echo "bad luck"
    elif [ $count -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi

    # Increment counter
    ((count++))
done
