#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

# Initialize variables
hour=0

# Use a while loop to iterate over hours from 0 to 12
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minute=1

    # Use a nested while loop to iterate over minutes from 1 to 59
    while [ $minute -le 59 ]
    do
        echo $minute
        ((minute++))
    done

    ((hour++))
done
