#!/usr/bin/env bash
# This script configures the localhost and facebook.com IP addresses on an Ubuntu server

# Change localhost IP
sudo sed -i 's/127\.0\.0\.1/127\.0\.0\.2/g' /etc/hosts

# Change existing entry for facebook.com IP to 8.8.8.8
sudo sed -i 's/^.*facebook\.com/8.8.8.8 facebook.com/g' /etc/hosts

