#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine

# Use ifconfig to get network interface information and filter out IPv4 addresses
ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | awk '{print $2}' | cut -d':' -f2

