#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine

# Use ifconfig to get network interface information and grep for lines containing 'inet'
# Filter out lines containing 'inet6' to exclude IPv6 addresses
# Use awk to extract the second field, which contains the IPv4 address
# Display the IPv4 addresses
ifconfig | grep 'inet ' | grep -v 'inet6' | awk '{print $2}'
