#!/usr/bin/env bash
# This script creates an RSA key pair

# Define variables
KEY_NAME="school"
BITS=4096
PASSPHRASE="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $BITS -N "$PASSPHRASE" -f "$KEY_NAME"

# Output success message
echo "RSA key pair created successfully."
